[package]
name = "router_example"
version = "0.1.0"
edition = "2021"

[dependencies]
makepad-widgets = { git = "https://github.com/wheregmis/makepad.git", branch = "makepad_router" }
makepad-router = { path = "../.." }
